### ISSUE TITLE
Placing menu pick of CurrentFullPath in a macro always returns the file in which the macro was recorded

### ISSUE THREAD

**Issue by cdellafera** [molsonkiko/NppCSharpPluginPack#7]
Placing menu pick of Current Full Path in a macro always returns the file in which the macro was recorded. I was a little surprised by this. I expected that when the macro was run in another editor tab (different file) that the macro would execute relative to the current editor tab and return the file name for that tab. This behavior seems anomalous to me, like either the file information is being cached at the time the macro is being recorded (less likely) or that the behavior of the macro is somehow relative to the editor tab in which it was recorded. Is there an NPP hook that can be called to make the Current Full Path relative to editor tab in which the macro is executed instead of the editor tab in which it was recorded?

**Comment by molsonkiko** [comment]
__Notepad++ ignores all plugin commands when recording macros__, except any text that is inserted or deleted by the plugin. This has always been true, probably will always be true, and is not the fault of the plugin. There is absolutely nothing (AFAIK) that any plugin can do to directly interact with the macro recorder, so I am closing this issue and will not reopen it.

If you want to know what messages actually *are* macroable, [you can look at this function in the source code](https://github.com/notepad-plus-plus/notepad-plus-plus/blob/f751ecaf04a9611fca1ed2ccefb1384893c7a5a0/PowerEditor/src/WinControls/shortcut/shortcut.cpp#L759).

Also, you  never need to guess what the macro recorder is doing in a macro; you can just go to `shortcuts.xml` (in your Notepad++ installation's application data folder) and [read the macros inside the `<Macros>` tab](https://npp-user-manual.org/docs/config-files/#macros) to read all the steps that were recorded.

So let's say that a plugin does the following after the user clicks the `BlahBlah` plugin command:
1. The macro recorder __does not__ record that the user clicked on the `BlahBlah` plugin command.
2. Reads some text in front of the caret, and calls `function1`, which returns `3` (the macro recorder __*does not*__ record this)
3. Based on the output of `function1`, deletes the `3` characters after the caret (the macro recorder __does__ record this)
4. Also based on the output of `function1`, moves the caret forward `2` characters (the macro recorder __does__ record this) 
5. Calls `someFunction` that takes those three characters and returns `foobar` (the macro recorder __*does not*__ record this)
6. Based on the output of `someFunction`, inserts `foobar` after the caret (the macro recorder __does__ record this)

Thus, the recorded macro *should always* do the following, assuming my understanding of the macro recorder is right:
1. Delete the `3` characters after the caret
2. Move the caret forward `2` characters
3. Insert `foobar` after the caret

The only "context-sensitive" thing you can do in a macro is pasting text using `SCI_PASTE` (i.e., the thing that happens when you use Ctrl+V or the `Paste` toolbar icon). That is the only macro action that I know of that uses any state outside of (a) the macro itself and (b) the text in the document as the macro is being executed. But of course, *this doesn't help you very much as a plugin author*, because even if you record a plugin command that populates the clipboard with some variable and then uses `SCI_PASTE` to insert the variable's value, the macro recorder will only remember `SCI_PASTE`, and ignore whatever internal logic the plugin used to decide what to paste.
